# name of the action
name: validate

# trigger on pull_request or push events
on:
  pull_request:
  push:

# pipeline to execute
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: clone
<<<<<<< HEAD
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
=======
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
>>>>>>> 2b2d0398193a806a0ae8c4a3c44a6e15f65c0568
    
    - name: install go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
      with:
        # use version from go.mod file
        go-version-file: 'go.mod'
        cache: true
        check-latest: true

    - name: validate
      run: |
        # Check that go mod tidy produces a zero diff; clean up any changes afterwards.
        go mod tidy && git diff --exit-code; code=$?; git checkout -- .; (exit $code)
        # Check that go vet ./... produces a zero diff; clean up any changes afterwards.
        go vet ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code)
        # Check that go fmt ./... produces a zero diff; clean up any changes afterwards.
        go fmt ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code)
        # Check that go fix ./... produces a zero diff; clean up any changes afterwards.
        go fix ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code)
